@extends('home/base.phtml')

<div class="container mt-3">
    <h1>Formulaire ajout category Ingredient</h1>
<form action="/catingredient/add" method="post">
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Category Ingredient :</label>
  <input type="text" class="form-control" name="category">
</div>
<input type="submit" class="btn btn-primary" name="ajout" value="Ajouter">
</form>
</div>