<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Formulaire Nutritionniste</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="css/styleNutritionniste.css" rel="stylesheet" />
    
    
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header">
                                    <h3 class="text-center font-weight-light my-4">Formulaire de modification Nutritionniste</h3>
                                    <?= var_dump($this->get('nutritionniste')->nom ); ?>
                                </div>
                                <div class="card-body">
                                    <form method="POST" action="/nutritionniste/update">
                                        <div class="row mb-3">
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input class="form-control" id="inputFirstName" 
                                                    type="text" name="nom" value="<?=  $this->get('nutritionniste')->nom ; ?>" />
                                                    <label for="inputFirstName">Nom</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-floating">
                                                    <input class="form-control" id="inputLastName" 
                                                    type="text" name="prenom" value="<?= $nutritionniste->getPrenom(); ?>"/>
                                                    <label for="inputLastName">Prenom</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" id="inputspecialite" 
                                            type="text" name="specialite" value="<?= $nutritionniste->getSpecialite(); ?>" />
                                            <label for="inputEmail">Spécialité</label>
                                        </div>
                                        <input type="hidden" name="id" value="<?= $this->get('nutritionniste')->getNutritionnisteId(); ?>">
                                        <div class="mt-4 mb-0">
                                            <div class="d-grid">
                                                <input type="submit" name="modifier" value="Modifier" class="btn btn-primary btn-block">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</body>
</html>