
<style>
    @import url("https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600;700;800;900;1000&family=Roboto:wght@300;400;500;700&display=swap");

*,
*::before,
*::after {
	box-sizing: border-box;
	padding: 0;
	margin: 0;
}

nav {
	user-select: none;
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	-o-user-select: none;
}

nav ul,
nav ul li {
	outline: 0;
}

nav ul li a {
	text-decoration: none;
}

body {
	font-family: "Nunito", sans-serif;
	display: flex;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
	background-image: url(https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg);
	background-repeat: no-repeat;
	background-size: cover;
    padding: 0;
    margin: 0;
	/* background: #212140; */
}

/* MAIN MENU */

main {
	display: grid;
	grid-template-columns: 13% 87%;
	min-height: 100vh;
	width: 100%;
	margin: 40px;
	background: rgb(254, 254, 254);
	box-shadow: 0 0.5px 0 1px rgba(255, 255, 255, 0.23) inset,
		0 1px 0 0 rgba(255, 255, 255, 0.66) inset, 0 4px 16px rgba(0, 0, 0, 0.12);
	border-radius: 15px;
	z-index: 10;
}

.main-menu {
	overflow: hidden;
	background: rgb(73, 57, 113);
	padding-top: 10px;
	border-radius: 15px 0 0 15px;
	font-family: "Roboto", sans-serif;
}

.main-menu h1 {
	display: block;
	font-size: 1.5rem;
	font-weight: 500;
	text-align: center;
	margin: 20px 0 30px;
	color: #fff;
	font-family: "Nunito", sans-serif;
}

.logo {
	display: none;
}

.nav-item {
	position: relative;
	display: block;
}

.nav-item a {
	position: relative;
	display: flex;
	flex-direction: row;
	align-items: center;
	justify-content: center;
	color: #fff;
	font-size: 1rem;
	padding: 15px 0;
	margin-left: 10px;
	border-top-left-radius: 20px;
	border-bottom-left-radius: 20px;
}

.nav-item b:nth-child(1) {
	position: absolute;
	top: -15px;
	height: 15px;
	width: 100%;
	background: #fff;
	display: none;
}

.nav-item b:nth-child(1)::before {
	content: "";
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	border-bottom-right-radius: 20px;
	background: rgb(73, 57, 113);
}

.nav-item b:nth-child(2) {
	position: absolute;
	bottom: -15px;
	height: 15px;
	width: 100%;
	background: #fff;
	display: none;
}

.nav-item b:nth-child(2)::before {
	content: "";
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	border-top-right-radius: 20px;
	background: rgb(73, 57, 113);
}

.nav-item.active b:nth-child(1),
.nav-item.active b:nth-child(2) {
	display: block;
}

.nav-item.active a {
	text-decoration: none;
	color: #000;
	background: rgb(254, 254, 254);
}

.nav-icon {
	width: 60px;
	height: 20px;
	font-size: 20px;
	text-align: center;
}

.nav-text {
	display: block;
	width: 120px;
	height: 20px;
	font-family: "Mulish", sans-serif;
}

@media (max-width: 800px) {
	.content {
		grid-template-columns: 52% 48%;
	}
}



</style>
<title>MANGER | Home</title>

<body>
	<main>
		<nav class="main-menu">
			<h1>MANGER</h1>
			<img class="logo" src="https://github.com/ecemgo/mini-samples-great-tricks/assets/13468728/4cfdcb5a-0137-4457-8be1-6e7bd1f29ebb" alt="" />
			<ul>
				<li class="nav-item active">
					<b></b>
					<b></b>
					<a href="#">
						<i class="fa fa-house nav-icon"></i>
						<span class="nav-text">Accueil</span>
					</a>
				</li>

				<li class="nav-item">
					<b></b>
					<b></b>
					<a href="#">
						<i class="fa fa-user nav-icon"></i>
						<span class="nav-text">Profil</span>
					</a>
				</li>

				<li class="nav-item">
					<b></b>
					<b></b>
					<a href="#">
						<i class="fa fa-calendar-check nav-icon"></i>
                    <span class="nav-text">Activités</span>
					</a>
				</li>

				<li class="nav-item">
					<b></b>
					<b></b>
					<a href="#">
						<i class="fa fa-sliders nav-icon"></i>
						<span class="nav-text">Paramètres</span>
					</a>
				</li>
			</ul>
		</nav>

		<section class="content">
            @content
			
		</section>
	</main>
</body>
<script>
    const navItems = document.querySelectorAll(".nav-item");

    navItems.forEach((navItem, i) => {
        navItem.addEventListener("click", () => {
            navItems.forEach((item, j) => {
                item.className = "nav-item";
            });
            navItem.className = "nav-item active";
        });
    });

</script>